upstream Backend {
    server orders-function.default.svc.cluster.local;
}

server {
    listen 0.0.0.0:80;
    listen [::]:80;
    default_type application/octet-stream;

    gzip on;
    gzip_comp_level 6;
    gzip_vary on;
    gzip_min_length 1000;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_buffers 16 8k;
    client_max_body_size 256M;

    root /usr/share/nginx/html;

    # API Proxy - Forward all API requests to Backend
    location ~* ^/(allOrders|saveOrder|getDeliveryOrderById)$ {
        proxy_pass http://Backend;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Upgrade "";
        proxy_set_header Host orders-function.default.127.0.0.1.sslip.io;
        access_log /var/log/nginx/api_debug.log;
    }

    # Default location for Angular app
    location / {
        try_files $uri /index.html;
    }
}
